/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JournalsRouteImport } from './routes/journals'
import { Route as AlgorithmsRouteImport } from './routes/algorithms'
import { Route as IndexRouteImport } from './routes/index'

const JournalsRoute = JournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsRoute = AlgorithmsRouteImport.update({
  id: '/algorithms',
  path: '/algorithms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/journals': typeof JournalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/journals': typeof JournalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/journals': typeof JournalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/algorithms' | '/journals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/algorithms' | '/journals'
  id: '__root__' | '/' | '/algorithms' | '/journals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgorithmsRoute: typeof AlgorithmsRoute
  JournalsRoute: typeof JournalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journals': {
      id: '/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof JournalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms': {
      id: '/algorithms'
      path: '/algorithms'
      fullPath: '/algorithms'
      preLoaderRoute: typeof AlgorithmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgorithmsRoute: AlgorithmsRoute,
  JournalsRoute: JournalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
